---
title: "What is machine learning?"
subtitle: "And why is it useful (for science)?"
author: "Grant Vagle, Jeremiah Shrovnal, Lynn Waterhouse"
institute: 
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Modeling mindsets:

**INSERT OVERVIEW OF MODELING MINDSETS**

.footnote[
 [1] [Molnar, C. Modeling mindsets: the many cultures of learning from data.](https://christophmolnar.com/books/modeling-mindsets)
]

---

# Machine learning is...

The mindset focused on prediction first


---

# For science, we often have multiple aims...

**INSERT HOW MINDSETS OVERLAP, especially how ML isn't just prediction (anymore)**


---

# Why prediction is a highly relevant aim for science



---

# Focus on supervised machine learning

Point to other techniques and their uses

Highlight supervised ML methods and their advantages for scientific questions


---

# Overview of the day




---

# Breakout groups (~5 min)

Talk with folks at your table:

- Names

- What modeling mindset(s) you typically use in your work

- What interests brought you to this workshop today

- Favorite body of water (anywhere, any type)
